[package]
name = "leptos-tiptap"
version = "0.3.0-alpha"
edition = "2021"
rust-version = "1.65.0"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/lpotthast/leptos-tiptap"
description = """
Tiptap integration for leptos projects.
"""
categories = ["gui"]
keywords = ["tiptap", "leptos", "components", "editor", "wysiwyg"]

[dependencies]
leptos = { git = "https://github.com/leptos-rs/leptos" }
serde = { version = "1.0.177", features = ["derive"] }
serde-wasm-bindgen = "0.5.0"
tracing = "0.1.37"
wasm-bindgen = "0.2.87"
